window.REFERENCE_CATALOG = [
  {
    id: "umamusume-us",
    name: "Umamusume: Pretty Derby",
    aliases: ["umamusume", "赛马娘", "pretty derby"],
    series: "umamusume",
    market: "US",
    observedMonths: 10,
    observedDownloads: 1895838,
    observedRevenue: 59923675.24,
    gameplayTags: ["sports", "training", "collector", "gacha", "rpg"],
    themeTags: ["anime", "horse-racing", "existing-ip"],
    monetization: "gacha_iap",
    audience: "midcore",
    lifecycle: "gacha_ip",
    sourceLabel: "US Android+iOS 上线至今样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/umamusume_us_since_launch_report.html",
    note: "观测窗口按 10 个完整月折算，来自 Sensor Tower 工作流样本报告。"
  },
  {
    id: "haikyu-us",
    name: "HAIKYU!! FLY HIGH",
    aliases: ["haikyu", "排球少年"],
    series: "haikyu",
    market: "US",
    observedMonths: 5,
    observedDownloads: 85061,
    observedRevenue: 1713814,
    gameplayTags: ["sports", "collector", "gacha", "card-battle"],
    themeTags: ["anime", "volleyball", "existing-ip"],
    monetization: "gacha_iap",
    audience: "midcore",
    lifecycle: "gacha_ip",
    sourceLabel: "US Android+iOS 近 5 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/us_umamusume_haikyu_bluelock_compare_report.html",
    note: "体育 IP 抽卡代表样本。"
  },
  {
    id: "blue-lock-us",
    name: "BLUE LOCK PWC",
    aliases: ["blue lock", "蓝色监狱"],
    series: "blue-lock",
    market: "US",
    observedMonths: 5,
    observedDownloads: 69693,
    observedRevenue: 418832,
    gameplayTags: ["sports", "collector", "gacha", "card-battle"],
    themeTags: ["anime", "football", "soccer", "existing-ip"],
    monetization: "gacha_iap",
    audience: "midcore",
    lifecycle: "gacha_ip",
    sourceLabel: "US Android+iOS 近 5 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/us_umamusume_haikyu_bluelock_compare_report.html",
    note: "体育 IP 抽卡代表样本。"
  },
  {
    id: "blue-archive-us",
    name: "Blue Archive",
    aliases: ["blue archive", "碧蓝档案"],
    series: "blue-archive",
    market: "US",
    observedMonths: 5,
    observedDownloads: 39078,
    observedRevenue: 1472962.47,
    gameplayTags: ["collector", "gacha", "rpg", "squad"],
    themeTags: ["anime", "school", "existing-ip"],
    monetization: "gacha_iap",
    audience: "midcore",
    lifecycle: "gacha_ip",
    sourceLabel: "US Android+iOS 近 5 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/4apps_US_Android_iOS_2025-11_to_2026-03_report.html",
    note: "二次元抽卡代表样本。"
  },
  {
    id: "nikke-us",
    name: "GODDESS OF VICTORY: NIKKE",
    aliases: ["nikke", "胜利女神"],
    series: "nikke",
    market: "US",
    observedMonths: 5,
    observedDownloads: 117610,
    observedRevenue: 14301519.76,
    gameplayTags: ["shooter", "collector", "gacha", "rpg"],
    themeTags: ["anime", "sci-fi", "existing-ip"],
    monetization: "gacha_iap",
    audience: "midcore",
    lifecycle: "gacha_ip",
    sourceLabel: "US Android+iOS 近 5 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/4apps_US_Android_iOS_2025-11_to_2026-03_report.html",
    note: "高 RPD 二次元样本。"
  },
  {
    id: "miku-us",
    name: "HATSUNE MIKU: COLORFUL STAGE!",
    aliases: ["hatsune miku", "初音未来", "colorful stage", "miku"],
    series: "miku",
    market: "US",
    observedMonths: 5,
    observedDownloads: 712122,
    observedRevenue: 2494675.84,
    gameplayTags: ["music", "rhythm", "collector", "gacha"],
    themeTags: ["anime", "idol", "existing-ip"],
    monetization: "gacha_iap",
    audience: "midcore",
    lifecycle: "gacha_ip",
    sourceLabel: "US Android+iOS 近 5 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/4apps_US_Android_iOS_2025-11_to_2026-03_report.html",
    note: "音游 IP 抽卡代表样本。"
  },
  {
    id: "pubg-latam",
    name: "PUBG Mobile",
    aliases: ["pubg", "pubg mobile", "吃鸡"],
    series: "pubg",
    market: "LATAM",
    observedMonths: 6,
    observedDownloads: 3618534,
    observedRevenue: 5201013,
    gameplayTags: ["shooter", "battle-royale", "fps", "pvp"],
    themeTags: ["military", "existing-ip"],
    monetization: "cosmetic_iap",
    audience: "midcore",
    lifecycle: "shooter_liveops",
    sourceLabel: "LATAM 近 6 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/pubg_latam_sea_report_6m.html",
    note: "拉美战术竞技代表样本。"
  },
  {
    id: "free-fire-latam",
    name: "Free Fire",
    aliases: ["free fire"],
    series: "free-fire",
    market: "LATAM",
    observedMonths: 6,
    observedDownloads: 20134433,
    observedRevenue: 53051606,
    gameplayTags: ["shooter", "battle-royale", "pvp"],
    themeTags: ["military"],
    monetization: "cosmetic_iap",
    audience: "midcore",
    lifecycle: "shooter_liveops",
    sourceLabel: "LATAM 近 6 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/pubg_latam_sea_report_6m.html",
    note: "拉美战术竞技代表样本。"
  },
  {
    id: "codm-latam",
    name: "Call of Duty Mobile",
    aliases: ["call of duty", "codm", "call of duty mobile"],
    series: "call-of-duty",
    market: "LATAM",
    observedMonths: 6,
    observedDownloads: 4555449,
    observedRevenue: 14212461,
    gameplayTags: ["shooter", "battle-royale", "fps", "pvp"],
    themeTags: ["military", "existing-ip"],
    monetization: "cosmetic_iap",
    audience: "midcore",
    lifecycle: "shooter_liveops",
    sourceLabel: "LATAM 近 6 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/pubg_latam_sea_report_6m.html",
    note: "拉美 FPS / 战术竞技代表样本。"
  },
  {
    id: "pubg-sea",
    name: "PUBG Mobile (SEA)",
    aliases: ["pubg", "pubg mobile", "吃鸡"],
    series: "pubg",
    market: "SEA",
    observedMonths: 6,
    observedDownloads: 6228381,
    observedRevenue: 10034596,
    gameplayTags: ["shooter", "battle-royale", "fps", "pvp"],
    themeTags: ["military", "existing-ip"],
    monetization: "cosmetic_iap",
    audience: "midcore",
    lifecycle: "shooter_liveops",
    sourceLabel: "SEA 近 6 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/pubg_latam_sea_report_6m.html",
    note: "东南亚战术竞技代表样本。"
  },
  {
    id: "free-fire-sea",
    name: "Free Fire (SEA)",
    aliases: ["free fire"],
    series: "free-fire",
    market: "SEA",
    observedMonths: 6,
    observedDownloads: 19617789,
    observedRevenue: 14220413,
    gameplayTags: ["shooter", "battle-royale", "pvp"],
    themeTags: ["military"],
    monetization: "cosmetic_iap",
    audience: "midcore",
    lifecycle: "shooter_liveops",
    sourceLabel: "SEA 近 6 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/pubg_latam_sea_report_6m.html",
    note: "东南亚战术竞技代表样本。"
  },
  {
    id: "coin-master-sea",
    name: "Coin Master",
    aliases: ["coin master"],
    series: "coin-master",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 3388923,
    observedRevenue: 20232650,
    gameplayTags: ["casual", "spinner", "board", "social"],
    themeTags: ["coin", "raid", "pets"],
    monetization: "hybrid_iap_ads",
    audience: "casual",
    lifecycle: "casual_hybrid",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "轻度 coin / spinner 代表样本。"
  },
  {
    id: "island-king-sea",
    name: "Island King",
    aliases: ["island king"],
    series: "island-king",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 176608,
    observedRevenue: 147979,
    gameplayTags: ["casual", "spinner", "board", "social"],
    themeTags: ["coin", "raid", "island"],
    monetization: "hybrid_iap_ads",
    audience: "casual",
    lifecycle: "casual_hybrid",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "轻度 coin / spinner 代表样本。"
  },
  {
    id: "crazy-fox-sea",
    name: "Crazy Fox",
    aliases: ["crazy fox"],
    series: "crazy-fox",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 134107,
    observedRevenue: 706242,
    gameplayTags: ["casual", "spinner", "board", "social"],
    themeTags: ["coin", "raid", "animals"],
    monetization: "hybrid_iap_ads",
    audience: "casual",
    lifecycle: "casual_hybrid",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "轻度 coin / spinner 代表样本。"
  },
  {
    id: "piggy-go-sea",
    name: "Piggy GO",
    aliases: ["piggy go"],
    series: "piggy-go",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 13138,
    observedRevenue: 272514,
    gameplayTags: ["casual", "spinner", "board", "social"],
    themeTags: ["coin", "travel", "animals"],
    monetization: "hybrid_iap_ads",
    audience: "casual",
    lifecycle: "casual_hybrid",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "轻度 coin / spinner 代表样本。"
  },
  {
    id: "archero-2-sea",
    name: "Archero 2",
    aliases: ["archero 2"],
    series: "archero",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 724611,
    observedRevenue: 3965404,
    gameplayTags: ["roguelite", "action", "survivor", "midcore"],
    themeTags: ["fantasy"],
    monetization: "hybrid_iap_ads",
    audience: "midcore",
    lifecycle: "roguelite_midcore",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "中核肉鸽代表样本。"
  },
  {
    id: "soul-knight-sea",
    name: "Soul Knight",
    aliases: ["soul knight", "元气骑士"],
    series: "soul-knight",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 480180,
    observedRevenue: 199932,
    gameplayTags: ["roguelite", "action", "shooter", "midcore"],
    themeTags: ["pixel", "fantasy"],
    monetization: "hybrid_iap_ads",
    audience: "midcore",
    lifecycle: "roguelite_midcore",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "中核肉鸽代表样本。"
  },
  {
    id: "survivor-io-sea",
    name: "Survivor.io",
    aliases: ["survivor.io", "survivor io"],
    series: "survivor-io",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 344826,
    observedRevenue: 621321,
    gameplayTags: ["roguelite", "survivor", "action", "midcore"],
    themeTags: ["apocalypse"],
    monetization: "hybrid_iap_ads",
    audience: "midcore",
    lifecycle: "roguelite_midcore",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "中核肉鸽代表样本。"
  },
  {
    id: "vampire-survivors-sea",
    name: "Vampire Survivors",
    aliases: ["vampire survivors"],
    series: "vampire-survivors",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 44626,
    observedRevenue: 12438,
    gameplayTags: ["roguelite", "survivor", "action"],
    themeTags: ["retro", "indie"],
    monetization: "premium",
    audience: "midcore",
    lifecycle: "premium_indie",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "买断肉鸽代表样本。"
  },
  {
    id: "archero-sea",
    name: "Archero",
    aliases: ["archero"],
    series: "archero",
    market: "SEA",
    observedMonths: 12,
    observedDownloads: 35175,
    observedRevenue: 171857,
    gameplayTags: ["roguelite", "action", "midcore"],
    themeTags: ["fantasy"],
    monetization: "hybrid_iap_ads",
    audience: "midcore",
    lifecycle: "roguelite_midcore",
    sourceLabel: "SEA 近 12 个月样本",
    sourceFile: "C:/Users/chenchen.zhang/.codex/skills/sensor-tower-workflow/sensortower-api/output/sea_coin_vs_roguelite_yearly_report.html",
    note: "中核肉鸽代表样本。"
  }
];
